title: webcomic
hero_image: images/banner.png
description: webcomic description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-26"
steps:
  - title: Introduction
  - title: What is a <div>?
  - title: Make a webcomic with HTML
  - title: Reflect
  - title: What next?
